name: Publish Docker image
on:
  push:
    branches: ['dev', 'master']
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: bcgov/ofi-tools/ofi-tools
          tag_with_ref: true
      - name: WebhookTest
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: distributhor/workflow-webhook@v1
        with:
          webhook_url: "https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dab7fb-tools/buildconfigs/ofi-dev-pipe-ocp-pipeline-deploy/webhooks/${{ secrets.DEV_PIPE_TOKEN }}/generic"
          webhook_secret: ${{ secrets.DEV_PIPE_TOKEN }}
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}", "commit": "$GITHUB_SHA" }'
      
      - name: WebhookDev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: distributhor/workflow-webhook@v1
        with:
          webhook_url: "https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dab7fb-tools/buildconfigs/ofi-test-pipe-ocp-pipeline-deploy/webhooks/${{ secrets.TEST_PIPE_TOKEN }}/generic"
          webhook_secret: ${{ secrets.TEST_PIPE_TOKEN }}
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}", "commit": "$GITHUB_SHA" }'