name: Publish Docker image
on:
  push:
    branches: ['dev', 'master']
  release:
    types: ['published']
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: bcgov/ofi-tools/ofi-tools
          tags: ${{github.sha}}
          tag_with_ref: true
      - name: Webhook Dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{ "env": [ { "name": "repository", "value": "${{github.event.repository.full_name}}"}, {"name": "commit", "value": "${{github.sha}}"} ] }' https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dab7fb-tools/buildconfigs/ofi-dev-pipe-ocp-pipeline-deploy/webhooks/${{ secrets.DEV_PIPE_TOKEN }}/generic
      
      - name: Webhook Test
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{ "env": [ { "name": "repository", "value": "${{github.event.repository.full_name}}"}, {"name": "commit", "value": "${{github.sha}}"} ] }' https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dab7fb-tools/buildconfigs/ofi-test-pipe-ocp-pipeline-deploy/webhooks/${{ secrets.TEST_PIPE_TOKEN }}/generic
      
      - name: Webhook PROD
        if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/head/dev' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{ "env": [ { "name": "repository", "value": "${{github.event.repository.full_name}}"}, {"name": "commit", "value": "${{github.ref}}"} ] }' https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dab7fb-tools/buildconfigs/ofi-prod-pipe-ocp-pipeline-deploy/webhooks/${{ secrets.PROD_PIPE_TOKEN }}/generic