name: Run linter

on:
  pull_request:
    branches: [dev, master]

jobs:
  lint:
    name: npm lint
    env:
      LINT_RESULTS: "No lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: lint
        run: |
          npm run lint | ${{ github.workspace }}/lint.txt
          pwd
          cat ${{ github.workspace }}/lint.txt >> ${{ env.LINT_RESULTS }}
          #test
          echo ${{ env.LINT_RESULTS }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ env.LINT_RESULTS }}`
            })